spring:
  # 데이터 베이스 
  datasource:
    url: jdbc:mysql://fpdb.c1mucyw28eav.ap-northeast-2.rds.amazonaws.com:3306/fpdb
    username: fpdb
    password: qwerasdf1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # sql:
  #   init:
  #     mode: always


  #  데이터 베이스 커넥션 
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect